inherit_from:
  - http://shopify.github.io/ruby-style-guide/rubocop.yml

AllCops:
  TargetRubyVersion: 2.3

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false
