---
name: krane
up:
  - ruby
  - bundler
  - podman
  - kind:
      name: krane
      image: kindest/node:v1.36.4@sha256:099e049362a1526b2db71494e1947aae99bd16290d7c895f2b7ea312e3cbfaed
commands:
  test:
    run: bin/test unit_test && bin/test cli_test && bin/test serial_integration_test && bin/test integration_test
  test-unit:
    run: bin/test unit_test
  test-cli:
    run: bin/test cli_test
  test-serial_integration:
    run: bin/test serial_integration_test,
  test-integration:
    run: bin/test integration_test
  tophat:
    run: PRINT_LOGS=1 bundle exec ruby -I test test/integration/krane_deploy_test.rb -n/${1}/
    desc: Tophat a change by running a test scenario with logging output enabled.
    syntax:
      optional:
        argument: TEST_REGEX
  doc:
    run: bundle exec yard doc
