---
name: kubernetes-deploy
up:
  - ruby: 2.4.6 # Matches gemspec
  - bundler
  - homebrew:
    - Caskroom/cask/minikube
  - custom:
      name: Install the minikube fork of driver-hyperkit
      met?: command -v docker-machine-driver-hyperkit
      meet: curl -LO https://storage.googleapis.com/minikube/releases/latest/docker-machine-driver-hyperkit && sudo install -o root -g wheel -m 4755 docker-machine-driver-hyperkit /usr/local/bin/ && rm ./docker-machine-driver-hyperkit
  - custom:
      name: Minikube Cluster
      met?: test $(minikube status | grep Running | wc -l) -ge 2 && $(minikube status | grep -q 'Correctly Configured')
      meet: minikube start --kubernetes-version=v1.11.6 --vm-driver=hyperkit
      down: minikube stop
commands:
  reset-minikube: minikube delete && rm -rf ~/.minikube
  test:
    run: bin/test
  tophat:
    run: PRINT_LOGS=1 bundle exec ruby -I test test/integration/krane_deploy_test.rb -n/${1}/
    desc: Tophat a change by running a test scenario with logging output enabled.
    syntax:
      optional:
        argument: TEST_REGEX
  doc:
    run: bundle exec yard doc
