---
name: krane
up:
  - ruby: '3.0.3' # Matches gemspec
  - bundler
  - podman
  - kind:
      name: krane
      image: kindest/node:v1.22.0@sha256:b8bda84bb3a190e6e028b1760d277454a72267a5454b57db34437c34a588d047
commands:
  test:
    run: bin/test
  tophat:
    run: PRINT_LOGS=1 bundle exec ruby -I test test/integration/krane_deploy_test.rb -n/${1}/
    desc: Tophat a change by running a test scenario with logging output enabled.
    syntax:
      optional:
        argument: TEST_REGEX
  doc:
    run: bundle exec yard doc
