---
name: kubernetes-deploy
up:
  - ruby: 2.3.3
  - bundler
  - homebrew:
    - Caskroom/cask/minikube
  - custom:
      name: Minikube Cluster
      met?: test $(minikube status | grep Running | wc -l) -eq 2 && $(minikube status | grep -q 'Correctly Configured')
      meet: minikube start --vm-driver=xhyve --kubernetes-version=v1.7.5
      down: minikube stop
commands:
  reset-minikube: minikube delete && rm -rf ~/.minikube
  test:
    run: bin/test
  tophat:
    run: PRINT_LOGS=1 bundle exec ruby -I test test/integration/kubernetes_deploy_test.rb -n/${1}/
    desc: Tophat a change by running a test scenario with logging output enabled.
    syntax:
      optional:
        argument: TEST_REGEX
