---
name: krane
up:
  - ruby
  - bundler
  - podman
  - kind:
      name: krane
      image: kindest/node:v1.34.3@sha256:08497ee19eace7b4b5348db5c6a1591d7752b164530a36f855cb0f2bdcbadd48
commands:
  test:
    run: bin/test unit_test && bin/test cli_test && bin/test serial_integration_test && bin/test integration_test
  test-unit:
    run: bin/test unit_test
  test-cli:
    run: bin/test cli_test
  test-serial_integration:
    run: bin/test serial_integration_test,
  test-integration:
    run: bin/test integration_test
  tophat:
    run: PRINT_LOGS=1 bundle exec ruby -I test test/integration/krane_deploy_test.rb -n/${1}/
    desc: Tophat a change by running a test scenario with logging output enabled.
    syntax:
      optional:
        argument: TEST_REGEX
  doc:
    run: bundle exec yard doc
