---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      deploy: example
  template:
    metadata:
      labels:
        deploy: example
    spec:
      containers:
        - name: nginx
          image: nginx
---
# kind: Deployment
# apiVersion: apps/v1
# metadata:
#   name: nginx-deployment-2
# spec:
#   selector:
#     matchLabels:
#       deploy: example-2
#   template:
#     metadata:
#       labels:
#         deploy: example-2
#     spec:
#       containers:
#         - name: nginx
#           image: nginx
