---
apiVersion: v1
kind: Endpoints
metadata:
  name: redis-endpoints
subsets:
  - addresses:
      - ip: 10.1.1.1
      - ip: 10.1.1.2
    ports:
      - name: redis
        port: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-endpoints
spec:
  clusterIP: None
  ports:
    - name: redis
      port: 6379
