shared: &shared
  retry:
     automatic:
       - exit_status: "*"
         limit: 1
steps:
  - name: 'Run Test Suite (:kubernetes: 1.11-latest)'
    <<: *shared
    command: bin/ci
    agents:
      queue: k8s-ci
    env:
      LOGGING_LEVEL: 4
      KUBERNETES_VERSION: v1.11-latest
  - name: 'Run Test Suite (:kubernetes: 1.10-latest)'
    <<: *shared
    command: bin/ci
    agents:
      queue: minikube-ci
    env:
      LOGGING_LEVEL: 4
      KUBERNETES_VERSION: v1.10-latest
  - name: 'Run Test Suite (:kubernetes: 1.9-latest)'
    <<: *shared
    command: bin/ci
    agents:
      queue: minikube-ci
    env:
      LOGGING_LEVEL: 4
      KUBERNETES_VERSION: v1.9-latest
  - name: 'Run Test Suite (:kubernetes: 1.8-latest)'
    <<: *shared
    command: bin/ci
    agents:
      queue: minikube-ci
    env:
      LOGGING_LEVEL: 4
      KUBERNETES_VERSION: v1.8-latest
