steps:
  - name: 'Run Test Suite (:kubernetes: 1.16-latest)'
    command: bin/ci
    agents:
      queue: k8s-ci
    env:
      LOGGING_LEVEL: 4
      KUBERNETES_VERSION: v1.16-latest
  - name: 'Run Test Suite (:kubernetes: 1.15-latest)'
    command: bin/ci
    agents:
      queue: k8s-ci
    env:
      LOGGING_LEVEL: 4
      KUBERNETES_VERSION: v1.15-latest
