steps:
  - name: 'Run Test Suite (:kubernetes: 1.14-latest)'
    command: bin/ci
    agents:
      queue: k8s-ci
    env:
      LOGGING_LEVEL: 4
      KUBERNETES_VERSION: v1.14-latest
  - name: 'Run Test Suite (:kubernetes: 1.13-latest)'
    command: bin/ci
    agents:
      queue: k8s-ci
    env:
      LOGGING_LEVEL: 4
      KUBERNETES_VERSION: v1.13-latest
  - name: 'Run Test Suite (:kubernetes: 1.12-latest)'
    command: bin/ci
    agents:
      queue: k8s-ci
    env:
      LOGGING_LEVEL: 4
      KUBERNETES_VERSION: v1.12-latest
  - name: 'Run Test Suite (:kubernetes: 1.11-latest)'
    command: bin/ci
    agents:
      queue: k8s-ci
    env:
      LOGGING_LEVEL: 4
      KUBERNETES_VERSION: v1.11-latest
  - name: 'Run Test Suite (:kubernetes: 1.10-latest)'
    command: bin/ci
    agents:
      queue: minikube-ci
    env:
      LOGGING_LEVEL: 4
      KUBERNETES_VERSION: v1.10-latest
  - name: ':rubocop: RuboCop'
    command: bundle install && bundle exec rubocop
    plugins:
      - docker#v3.2.0:
        image: "circleci/ruby:2.6.3-node"
