#!/usr/bin/env ruby
# frozen_string_literal: true

require 'optparse'

require 'kubernetes-deploy'
require 'kubernetes-deploy/restart_task'

raw_deployments = nil
ARGV.options do |opts|
  opts.on("--deployments=LIST") { |v| raw_deployments = v.split(",") }
  opts.parse!
end

namespace = ARGV[0]
context = ARGV[1]
logger = KubernetesDeploy::FormattedLogger.build(namespace, context)

restart = KubernetesDeploy::RestartTask.new(namespace: namespace, context: context, logger: logger)
begin
  restart.perform!(raw_deployments)
rescue KubernetesDeploy::DeploymentTimeoutError
  exit 124
rescue KubernetesDeploy::FatalDeploymentError
  exit 1
end
