#!/usr/bin/env ruby
# frozen_string_literal: true

require 'optparse'

require 'kubernetes-deploy'
require 'kubernetes-deploy/restart_task'

raw_deployments = nil
max_watch_seconds = nil
selector = nil
ARGV.options do |opts|
  opts.on("--deployments=LIST") { |v| raw_deployments = v.split(",") }
  opts.on("--max-watch-seconds=seconds") { |t| max_watch_seconds = t.to_i }
  opts.on("--selector=SELECTOR", "Restarts deployments matching selector (format: k1=v1,k2=v2 or JSON)") do |s|
    selector = KubernetesDeploy::LabelSelector.parse(s)
  end
  opts.parse!
end

namespace = ARGV[0]
context = ARGV[1]
logger = KubernetesDeploy::FormattedLogger.build(namespace, context)

restart = KubernetesDeploy::RestartTask.new(namespace: namespace, context: context, logger: logger,
   max_watch_seconds: max_watch_seconds)
begin
  restart.perform!(raw_deployments, selector: selector)
rescue KubernetesDeploy::DeploymentTimeoutError
  exit(70)
rescue KubernetesDeploy::FatalDeploymentError
  exit(1)
end
